### ISSUE TITLE
Package up GLM outputs to share for use in the next couple of weeks

### ISSUE THREAD

**Issue by lindsayplatt** [DOI-USGS/lake-temperature-process-models#20]
We talked about creating a zip file of individual lake feathers per tile

**Comment by jordansread** [comment]
Sounds good for an interim (and maybe final?) solution, but I'd like the opportunity to revisit this before it becomes a final decision for a data release. I could weigh in here for my reasoning on that, but am not doing so now because it seems like a detour on current priorities and sharing with our internal collaborators (Gretchen et al) can be well served with the current plan.

**Comment by hcorson-dosch-usgs** [comment]
I'm thinking about how to set up the dependency tracking to create these zip files, and my initial thinking was that it might make sense to go the tibble route (with data hash) for the [output feather file targets](https://github.com/hcorson-dosch/lake-temperature-process-models/blob/main/2_run.R#L29-L37), since we'll only want to package up those that succeed (some will fail b/c the failed runs will have NA for the `export_fl` field). That way we could group the tibble by `tile_no` (assuming we carry `tile_no` all the way through the pipeline).

As I think through it I'm seeing 2 issues:

1) To package up all the output on Caldera, the tibble with data hash and `tile_no` approach would require re-running the models (to get that `tile_no` field in `p2_glm_uncalibrated_runs`, and thus passed through to `p2_glm_uncalibrated_output_feathers`) , so a workaround  (keeping `p2_glm_uncalibrated_output_feathers` a file target and creating a new tibble target from that vector, with a data hash and joining `tile_no` based on `cell_no`) might be the best solution?

2) I'm not certain how well object targets that return tibbles play with `error='continue'`. When I set `error='continue'` for p2_glm_uncalibrated_runs on Denali I couldn't get the tibble to load afterward  - I could test a bit locally to see if it's actually an issue or not.

I guess the key is that we want to generate a zip folder for each tile, regardless of whether every lake within that tile has output, but we also only want to update that zip folder if a) more lakes within that tile have output, or b) that output changes

**Comment by lindsayplatt** [comment]
@jread-usgs the idea of using NetCDF-DSG for sharing is still on the table but not for our current timeline as you noted in a previous comment. I'll edit this issue name to make that clear. I was opening this mostly to create a space for @hcorson-dosch and I to troubleshoot some tricky pieces outside of MS Teams.

**Comment by hcorson-dosch-usgs** [comment]
Shoot just realized that `cell_no` isn't included in the current [export tibble](https://github.com/hcorson-dosch/lake-temperature-process-models/blob/main/2_run/src/run_glm3.R#L152-L169) 😖, so that, like `tile_no` would require a rebuild 🤦‍♀️ but we could instead join the `lake_cell_tile_xwalk` using the lake ids.

**Comment by lindsayplatt** [comment]
1. If we really wanted the `tile_no` and `cell_no` to be part of the export tibble, I think it would be worth a rebuild rather than coding in a workaround. Though, I think it might be OK to not have `tile_no` or `cell_no` in the export tibbles and join those in based on the lake id after. We may want to bundle the outputs differently in the future, so I think leaving that join as a step later would be fine. 
2. I might not have this right but I believe `error = "continue"` skips a failing branch to keep building others but still doesn't allow the final overall branch target to build. So, I think we want to be catching the failed ones ourselves and logging them as you do [here](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/run_glm3.R#L128-L194), so that none actually error in the way that `targets` would catch with `error = "continue"` for the branching target. My suggestion would be [filtering the combined export tibble](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run.R#L24) by [`glm_success`](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/run_glm3.R#L168) before using them in anything else.

**Comment by hcorson-dosch-usgs** [comment]
K I'm testing with a hybrid approach now, generating a tibble for `glm_uncalibrated_output_feathers` and then making a new grouped target that joins in `tile_no` based on lake id and groups by `tile_no`, so we'll see how that works.

👍 to catching any errors in the call to [combine the GLM output](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/process_glm_output.R#L15-L33) ourselves in `tryCatch()`, but I don't think we want to filter the `p2_glm_uncalibrated_runs` tibble by `glm_success` _unless_ we want to package up output for a given lake-gcm combo even if one of the 3 runs associated with that combo failed. As we have it set  up, we only generate an [output_feather](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run.R#L29-L37) for a lake-gcm combo if we have predictions for all 3 time periods.

**Comment by lindsayplatt** [comment]
> we only generate an [output_feather](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run.R#L29-L37) for a lake-gcm combo if we have predictions for all 3 time periods

After looking at [the target recipe](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run.R#L31-L36) and [the function called](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/process_glm_output.R), I don't see where this limitation is being enforced?  I think we can use `glm_success` for the groups to not package up a lake-gcm if any of the combos failed by adding `filter(all(glm_success))` right after your grouping line [here](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run.R#L25)

**Comment by hcorson-dosch-usgs** [comment]
Right now it's done indirectly, b/c if a run has failed it has `NA` for `export_fl`, which then triggers an error when we try to [read that file in](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/process_glm_output.R#L28), which then means the target fails. Definitely cleaner to switch to `filter(all(glm_success))`, so will switch to that.

**Comment by lindsayplatt** [comment]
Ahhhhhhhhh ok, hence you needing `error = "continue"` and not being able to `tar_load(p2_glm_uncalibrated_output_feathers)` after building. Yes, I think we want to do some of our own filtering ahead of time to prevent that error with NA rather than let `error = "continue"` be part of our workflow for known issues.
