### ISSUE TITLE
Looking for `lake_cell_tile_xwalk.csv` and `GCM_{gcm name}.nc` for MO models

### ISSUE THREAD

**Issue by padilla410** [DOI-USGS/lake-temperature-process-models#66]
I am trying to find the following files:
* `7_drivers_munge/out/lake_cell_tile_xwalk.csv`
* `7_drivers_munge/out/GCM_{gcm name}.nc`

So that I can set up a file structure similar to the one outlined in this repo's `README.md`. I do not have them in my local copy of `lake-temperature-model-prep` nor was I able to find them on the google drive for `lake-temperature-model-prep`.

@hcorson-dosch do you know where these files live? _Or_ am I totally missing something here? I would appreciate any advice you might have to offer.

**Comment by hcorson-dosch-usgs** [comment]
Hi Julie - those files pertain _only_ to the _GCM portion_ of the workflow in this repo, which generates GLM predictions using GCM driver data for contemporary and future time periods (noted as 'future-casting' lake temperatures in our task sheet). Those files you listed above are used to match each lake to the correct GCM driver data. 

Since you're working w/ NLDAS to hindcast temperatures in MO reservoirs you won't need those files. Instead you can use the `meteo_fl` field specified for each lake in the `nml_list.rds` (here `p1_nml_list_rds`) to identify the correct NLDAS meteo data for each lake's simulation. That's the workflow set up for NLDAS model runs in this repo.

**Comment by padilla410** [comment]
Great! Thank you!
